flatcar: support Nvidia fabric manager

diff --git a/flatcar/nvidia-driver b/flatcar/nvidia-driver
--- a/flatcar/nvidia-driver
+++ b/flatcar/nvidia-driver
@@ -72,6 +72,15 @@ _is_flatcar() {
     nsenter -t 1 -m grep -q 'ID=flatcar' /etc/os-release
 }
 
+# Check if the system is NVSwitch based (e.g. HGX/DGX A100, H100, H200).
+_assert_nvswitch_system() {
+    [ -d /proc/driver/nvidia-nvswitch/devices ] || return 1
+    if [ -z "$(ls -A /proc/driver/nvidia-nvswitch/devices)" ]; then
+        return 1
+    fi
+    return 0
+}
+
 
 _fetch_flatcar_modules() {
     local versionid=${1-}
@@ -293,6 +302,11 @@ _load_driver() {
 
     echo "Starting NVIDIA persistence daemon..."
     nvidia-persistenced --persistence-mode
+
+    if _assert_nvswitch_system; then
+        echo "Starting NVIDIA fabric manager daemon..."
+        nv-fabricmanager -c /usr/share/nvidia/nvswitch/fabricmanager.cfg
+    fi
 }
 
 # Stop persistenced and unload the kernel modules if they are currently loaded.
@@ -315,6 +329,22 @@ _unload_driver() {
         done
         if [ "$i" -eq 10 ]; then
             echo "Could not stop NVIDIA persistence daemon" >&2
+            return 1
+        fi
+    fi
+
+    if [ -f /var/run/nvidia-fabricmanager/nv-fabricmanager.pid ]; then
+        echo "Stopping NVIDIA fabric manager daemon..."
+        local pid
+        pid=$(< /var/run/nvidia-fabricmanager/nv-fabricmanager.pid)
+
+        kill -SIGTERM "${pid}"
+        for i in $(seq 1 50); do
+            kill -0 "${pid}" 2> /dev/null || break
+            sleep 0.1
+        done
+        if [ "$i" -eq 50 ]; then
+            echo "Could not stop NVIDIA fabric manager daemon" >&2
             return 1
         fi
     fi
